---
abstract: 'It provides before/after hooks of subtest.'
author:
  - 'ainame <ainame954@facebook.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.1.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-More-Hooks
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Test::More::Hooks:
    file: lib/Test/More/Hooks.pm
    version: 0.04
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/ainame/p5-Test-More-Hooks/issues
  homepage: https://github.com/ainame/p5-Test-More-Hooks
  repository: git://github.com/ainame/p5-Test-More-Hooks.git
version: 0.04
